# Generated by Django 3.2.16 on 2022-11-28 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('device_information_id', models.IntegerField(max_length=100)),
                ('allot_date', models.DateField()),
                ('expired_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Device_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_information_id', models.IntegerField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('user_id', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hosting_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('device_id', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mapping_Server_Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_information_id', models.IntegerField(max_length=100)),
                ('mobile_information_id', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('device_id', models.IntegerField(max_length=100)),
                ('serial_number', models.IntegerField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('location_of_hosting', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('server_device_id', models.IntegerField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('updated_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Procurement_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(max_length=100)),
                ('device_type', models.CharField(max_length=100)),
                ('types', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('device_id', models.IntegerField(max_length=100)),
                ('number_days', models.IntegerField(max_length=100)),
                ('request_date', models.DateField()),
                ('request_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Server_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('device_id', models.IntegerField(max_length=100)),
                ('serial_number', models.IntegerField(max_length=100)),
                ('server_capacity', models.IntegerField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('location_of_hosting', models.CharField(max_length=100)),
                ('date_of_purchase', models.DateField()),
                ('updated_date', models.DateField()),
            ],
        ),
    ]
